mcset nl "Widget Demonstration" "Demonstratie van widgets"
mcset nl "tkWidgetDemo" "tkWidgetDemo"
mcset nl "&File"     "&Bestand"
mcset nl "About..."  "Info..."
mcset nl "&About..." "&Info..."
mcset nl "<F1>"      "<F1>"
mcset nl "&Quit"     "&Einde"
mcset nl "Meta+Q"    "Meta+E"		;# Displayed hotkey
mcset nl "Meta-q"    "Meta-e"		;# Actual binding sequence
mcset nl "Ctrl+Q"    "Ctrl+E"		;# Displayed hotkey
mcset nl "Control-q" "Control-e"	;# Actual binding sequence
mcset nl "Dismiss"   "Sluiten"
mcset nl "See Variables"    "Bekijk Variabelen"
mcset nl "Variable Values"  "Waarden Variabelen"
mcset nl "OK"        "OK"
mcset nl "Run the \"%s\" sample program" "Start voorbeeld \"%s\""
mcset nl "Print Code" "Code Afdrukken"
mcset nl "Demo code: %s" "Code van Demo %s"
mcset nl "About Widget Demo" "Over deze demonstratie"
mcset nl "Tk widget demonstration" "Demonstratie van Tk widgets"
mcset nl "Copyright (c) %s" "Copyright (c) %s"

mcset nl "Tk Widget Demonstrations" "Demostratie van Tk widgets"
mcset nl "This application provides a front end for several short scripts" \
	"Dit programma is een schil rond enkele korte scripts waarmee"
mcset nl "that demonstrate what you can do with Tk widgets.  Each of the" \
	"gedemonstreerd wordt wat je kunt doen met Tk widgets.  Elk van de"
mcset nl "numbered lines below describes a demonstration;  you can click on" \
	"genummerde regels hieronder omschrijft een demonstratie;  je kunt de"
mcset nl "it to invoke the demonstration.  Once the demonstration window" \
	"demonstratie starten door op de regel te klikken."
mcset nl "appears, you can click the" \
	"Zodra het nieuwe venster verschijnt, kun je op de knop"
mcset nl "See Code"  "Bekijk Code"	;# This is also button text!
mcset nl "button to see the Tcl/Tk code that created the demonstration.  If" \
	"drukken om de achterliggende Tcl/Tk code te zien.  Als je dat wilt,"
mcset nl "you wish, you can edit the code and click the" \
	"kun je de code wijzigen en op de knop"
mcset nl "Rerun Demo" "Herstart Demo"	;# This is also button text!
mcset nl "button in the code window to reinvoke the demonstration with the" \
	"drukken in het codevenster om de demonstratie uit te voeren met de"
mcset nl "modified code." \
	"nieuwe code."

mcset nl "Labels, buttons, checkbuttons, and radiobuttons" \
         "Labels, knoppen, vinkjes/aankruishokjes en radioknoppen"

mcset nl "Labels (text and bitmaps)" "Labels (tekst en plaatjes)"
mcset nl "Labels and UNICODE text"   "Labels en tekst in UNICODE"
mcset nl "Buttons" "Buttons (drukknoppen)"
mcset nl "Check-buttons (select any of a group)" "Check-buttons (een of meer uit een groep)"
mcset nl "Radio-buttons (select one of a group)" "Radio-buttons (een van een groep)"
mcset nl "A 15-puzzle game made out of buttons"  "Een schuifpuzzel van buttons"
mcset nl "Iconic buttons that use bitmaps"       "Buttons met pictogrammen"
mcset nl "Two labels displaying images"          "Twee labels met plaatjes in plaats van tekst"
mcset nl "A simple user interface for viewing images" \
         "Een eenvoudige user-interface voor het bekijken van plaatjes"
mcset nl "Labelled frames"                       "Kaders met bijschrift"

mcset nl "Listboxes" "Keuzelijsten"
mcset nl "The 50 states" "De 50 staten van de VS"
mcset nl "Colors: change the color scheme for the application" \
         "Kleuren: verander het kleurenschema voor het programma"
mcset nl "A collection of famous and infamous sayings" \
         "Beroemde en beruchte citaten en gezegden"

mcset nl "Entries and Spin-boxes"     "Invulvelden en Spinboxen"
mcset nl "Entries without scrollbars" "Invulvelden zonder schuifbalk"
mcset nl "Entries with scrollbars"    "Invulvelden met schuifbalk"
mcset nl "Validated entries and password fields" \
         "Invulvelden met controle of wachtwoorden"
mcset nl "Spin-boxes" "Spinboxen"
mcset nl "Simple Rolodex-like form" "Simpel kaartsysteem"

mcset nl "Text" "Tekst"
mcset nl "Basic editable text" "Voorbeeld met te wijzigen tekst"
mcset nl "Text display styles" "Tekst met verschillende stijlen"
mcset nl "Hypertext (tag bindings)" "Hypertext (verwijzingen via \"tags\")"
mcset nl "A text widget with embedded windows" \
         "Tekstwidget met windows erin"
mcset nl "A search tool built with a text widget" \
         "Zoeken in tekst met behulp van een tekstwidget"

mcset nl "Canvases" "Canvaswidgets"
mcset nl "The canvas item types"     "Objecten in een canvas"
mcset nl "A simple 2-D plot"         "Eenvoudige 2D-grafiek"
mcset nl "Text items in canvases"    "Tekstobjecten in een canvas"
mcset nl "An editor for arrowheads on canvas lines" \
         "Editor voor de vorm van de pijl (begin/eind van een lijn)"
mcset nl "A ruler with adjustable tab stops" \
         "Een meetlat met aanpasbare ruiters"
mcset nl "A building floor plan"     "Plattegrond van een gebouw"
mcset nl "A simple scrollable canvas" "Een schuifbaar canvas"

mcset nl "Scales" "Schaalverdelingen"
mcset nl "Horizontal scale"          "Horizontale schaal"
mcset nl "Vertical scale"          "Verticale schaal"

mcset nl "Paned Windows" "Vensters opgedeeld in stukken"
mcset nl "Horizontal paned window"   "Horizontaal gedeeld venster"
mcset nl "Vertical paned window"     "Verticaal gedeeld venster"

mcset nl "Menus" "Menu's"
mcset nl "Menus and cascades (sub-menus)" \
         "Menu's en cascades (submenu's)"
mcset nl "Menu-buttons" "Menu-buttons"

mcset nl "Common Dialogs" "Veel voorkomende dialoogvensters"
mcset nl "Message boxes"  "Mededeling (message box)"
mcset nl "File selection dialog"     "Selectie van bestanden"
mcset nl "Color picker"              "Kleurenpalet"

mcset nl "Miscellaneous"             "Diversen"
mcset nl "The built-in bitmaps"      "Ingebouwde plaatjes"
mcset nl "A dialog box with a local grab" \
         "Een dialoogvenster met een locale \"grab\""
mcset nl "A dialog box with a global grab" \
         "Een dialoogvenster met een globale \"grab\""
