.\" You can view this file with:
.\" nroff -man [filename]
.\"
.TH svnlook 1
.SH NAME
svnlook \- Subversion repository examination tool
.SH SYNOPSIS
.TP
\fBsvnlook\fP \fIcommand\fP \fI/path/to/repos\fP [\fIoptions\fP] [\fIargs\fP]
.SH OVERVIEW
Subversion is a version control system, which allows you to keep old
versions of files and directories (usually source code), keep a log of
who, when, and why changes occurred, etc., like CVS, RCS or SCCS.
\fBSubversion\fP keeps a single copy of the master sources.  This copy
is called the source ``repository''; it contains all the information
to permit extracting previous versions of those files at any time.

For more information about the Subversion project, visit 
http://subversion.tigris.org.

Documentation for Subversion and its tools, including detailed usage
explanations of the \fBsvn\fP, \fBsvnadmin\fP, \fBsvnserve\fP and
\fBsvnlook\fP programs, historical background, philosophical 
approaches and reasonings, etc., can be found at 
http://svnbook.red-bean.com/.

Run `svnlook help' to access the built-in tool documentation.
