diff --git a/win32/makefile.mk b/win32/makefile.mk
index 6b48805..27c143b 100644
--- a/win32/makefile.mk
+++ b/win32/makefile.mk
@@ -23,12 +23,12 @@
 # newly built perl.
 #
 INST_DRV	*= c:
-INST_TOP	*= $(INST_DRV)\perl
+INST_TOP	*= @ROOT@\mingw\perl
 
 #
 # Uncomment if you want to build a 32-bit Perl using a 32-bit compiler
 # on a 64-bit version of Windows.
-#WIN64		*= undef
+WIN64		*= undef
 
 #
 # Comment this out if you DON'T want your perl installation to be versioned.
@@ -217,7 +217,7 @@ CRYPT_SRC	*= fcrypt.c
 .IF "$(CCTYPE)" == "BORLAND"
 CCHOME		*= C:\Borland\BCC55
 .ELIF "$(CCTYPE)" == "GCC"
-CCHOME		*= C:\MinGW
+CCHOME		*= @ROOT@\mingw
 .ELSE
 CCHOME		*= $(MSVCDIR)
 .ENDIF
@@ -233,8 +233,8 @@ CCHOME		*= $(MSVCDIR)
 # unsure about the correct name.)
 # Without these corrections, the op/taint.t test script will fail.
 #
-#GCC_4XX		*= define
-#GCCHELPERDLL	*= $(CCHOME)\bin\libgcc_s_sjlj-1.dll
+GCC_4XX		*= define
+GCCHELPERDLL	*= $(CCHOME)\bin\libgcc_s_sjlj-1.dll
 #GCCHELPERDLL	*= $(CCHOME)\bin\libgcc_s_dw2-1.dll
 #GCCHELPERDLL	*= $(CCHOME)\bin\libgcc_s_1.dll
 
