.\"     Title: ne_has_support
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 20 August 2008
.\"    Manual: neon API reference
.\"    Source: neon 0.28.3
.\"
.TH "NE_HAS_SUPPORT" "3" "20 August 2008" "neon 0.28.3" "neon API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ne_has_support - determine feature support status
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <ne_utils\.h>
.fi
.ft
.HP 19
.BI "int ne_has_support(int\ " "feature" ");"
.SH "DESCRIPTION"
.PP
The
\fBne_has_support\fR
function can be used to determine whether a particular optional feature, given by the feature code
\fIfeature\fR, is supported\. The following feature codes are available:
.PP
\fBNE_FEATURE_SSL\fR
.RS 4
Indicates support for SSL/TLS
.RE
.PP
\fBNE_FEATURE_ZLIB\fR
.RS 4
Indicates support for compressed responses
.RE
.PP
\fBNE_FEATURE_IPV6\fR
.RS 4
Indicates support for IPv6
.RE
.PP
\fBNE_FEATURE_LFS\fR
.RS 4
Indicates support for large files
.RE
.PP
\fBNE_FEATURE_SOCKS\fR
.RS 4
Indicates support for SOCKSv5
.RE
.PP
\fBNE_FEATURE_TS_SSL\fR
.RS 4
Indicates support for thread\-safe SSL initialization \(em see
ne_sock_init
.RE
.SH "RETURN VALUE"
.PP
\fBne_has_support\fR
returns non\-zero if the given feature is supported, or zero otherwise\.
.SH "SEE ALSO"
.PP
ne_version_match(3),
ne_sock_init(3)
.SH "AUTHOR"
.PP
\fBJoe Orton\fR <\&neon@lists.manyfish.co.uk\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
