.TH SSH-PKCS11-HELPER 8 "July 16 2013 " ""
.SH NAME
\fBssh-pkcs11-helper\fP
\- ssh-agent helper program for PKCS#11 support
.SH SYNOPSIS
.br
\fBssh-pkcs11-helper\fP
.SH DESCRIPTION
\fBssh-pkcs11-helper\fP
is used by
\fBssh-agent\fP(1)
to access keys provided by a PKCS#11 token.

\fBssh-pkcs11-helper\fP
is not intended to be invoked by the user, but from
\fBssh-agent\fP(1).
.SH SEE ALSO
\fBssh\fP(1),
\fBssh-add\fP(1),
\fBssh-agent\fP(1)
.SH HISTORY
\fBssh-pkcs11-helper\fP
first appeared in
OpenBSD 4.7 .
.SH AUTHORS

Markus Friedl <Mt markus@openbsd.org>
